# Generated by Django 5.1.3 on 2024-12-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parking_images/'),
        ),
    ]
